#===============================================================================
# Tandem Tales Agent (Python) Compose Configuration
# 
# Defines how to run a Tandem Tales web server and a Python agent that connects
# to that server. This configuration is meant for development and testing.
#===============================================================================
services:
  # Python agent configuration
  agent:
    image: tt-random-agent-python
    build:
      # Use the Dockerfile in this directory.
      context: .
      # Target the 'dev' stage inthe Dockerfile.
      target: dev
    # Wait for the server to start before starting this agent.
    depends_on:
      server:
        condition: service_healthy
        restart: true
    # Join the TT server network so they share the same 'localhost'.
    network_mode: "service:server"
    # Environment variables in this file will be defined at container run time.
    env_file:
      - .env
    # Volumes are special directories from the host or other containers.
    volumes:
      # The public key from the server is in this shared volume.
      - certs:/etc/tt/certs
      # The agent's source code is here. You can edit it at run time!
      - ./root/app:/app
    # Make this container interactive when it starts.
    stdin_open: true
    tty: true
  # Tandem Tales server configuration
  server:
    image: tt-web
    # Configure the server's environment variables.
    environment:
      # Add an agent with these values to the database.
      - agent_name=${name}
      - agent_password=${password-}
      - agent_title=${title-}
      - agent_description=${description-}
      # Set up the quick play link on the homepage.
      - play_world=${world-}
      - agent_role=${role-}
      - play_partner=${name-}
    # Volumes are special directories from the host or other containers.
    volumes:
      # This shared volume contains the server's public key so the agent can use it.
      - certs:/etc/tt/certs
    # Allow the container to accept incoming network connections on these ports.
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "9005:9005" # Tandem Tales
      - "9006:9006" # Tandem Tales (WebSockets)
    # Detect when the server has started.
    healthcheck:
      test: ["CMD-SHELL", "grep -q \"Server now listening\" /var/log/tt/log.txt && exit 0 || exit 1"]
      interval: 500ms
      timeout: 1s
      retries: 10
# Volumes shared between containers are defined here.
volumes:
  # This volume contains the server's public key so it can be used by both server and agent.
  certs: